version: '3.8'

services:
  # 1. THE MESSAGE BROKER
  kafka:
    image: apache/kafka:latest
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      # We advertise the service name 'kafka' so other containers can find it
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  # 2. THE CACHE & PUB/SUB ROUTER
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-cache
    ports:
      - "6379:6379"

  # 3. YOUR MAIN API SERVER
  chat-api-1:
    build: ./backend
    container_name: chat-api-1
    environment:
      - PORT=5000
      - KAFKA_BROKER=kafka:9092
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./backend/.env
    depends_on:
      - kafka
      - redis

  chat-api-2:
    build: ./backend
    container_name: chat-api-2
    environment:
      - PORT=5000
      - KAFKA_BROKER=kafka:9092
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./backend/.env
    depends_on:
      - kafka
      - redis

  chat-api-3:
    build: ./backend
    container_name: chat-api-3
    environment:
      - PORT=5000
      - KAFKA_BROKER=kafka:9092
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./backend/.env
    depends_on:
      - kafka
      - redis
  # 4. THE DATABASE WORKER
  db-worker:
    build: ./backend
    container_name: chat-db-worker
    # We override the default "npm start" to run the worker instead
    command: node src/worker.js 
    environment:
      - KAFKA_BROKER=kafka:9092
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./backend/.env
    depends_on:
      - kafka
      - redis

  # 5. THE ANALYTICS WORKER
  analytics-worker:
    build: ./backend
    container_name: chat-analytics-worker
    command: node src/analytics-worker.js
    environment:
      - KAFKA_BROKER=kafka:9092
    env_file:
      - ./backend/.env
    depends_on:
      - kafka
# 6. THE LOAD BALANCER (The new front door)
  nginx:
    image: nginx:latest
    container_name: chat-load-balancer
    ports:
      - "80:80"  # This is the ONLY port exposed to the outside world now!
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - chat-api-1
      - chat-api-2
      - chat-api-3